### Login
POST http://127.0.0.1:8000/api/account/login
content-type: application/json

{
  "name": "new_account",
  "password": "testing132"
}

### Register

POST http://127.0.0.1:8000/api/account/register
content-type: application/json

{
  "name": "new_account",
  "email": "new@example.com",
  "password": "testing132"
}

### Info

POST http://127.0.0.1:8000/api/account/info
content-type: application/json

{
  "user_id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df"
}

### item get
POST http://127.0.0.1:8000/api/items/get
content-type: application/json

{
  "user_id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df",
  "item_id": 1
}

### item all
GET http://127.0.0.1:8000/api/items/all

### cart get
POST http://127.0.0.1:8000/api/cart/get
content-type: application/json

{
  "user_id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df"
}

### cart set
POST http://127.0.0.1:8000/api/cart/set
content-type: application/json

{
  "user_id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df",
  "item_id": 2,
  "quantity": 69
}

### cart del
POST http://127.0.0.1:8000/api/cart/del
content-type: application/json

{
  "user_id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df",
  "item_id": 2
}

### cart clean
POST http://127.0.0.1:8000/api/cart/clean
content-type: application/json

{
  "user_id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df"

}
### cart checkout
POST http://127.0.0.1:8000/api/cart/checkout
content-type: application/json

{
  "user_id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df"
}

### shopping all
POST http://127.0.0.1:8000/api/shopping/all

{
  "id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df"
}

### shopping get
POST http://127.0.0.1:8000/api/shopping/get

{
  "id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df",
  "order_id": 1
}

### shipping all
POST http://127.0.0.1:8000/api/shipping/all

{
  "id": 5,
  "session": "28ee014d-12cd-41ff-9121-7a722162a1df"
}