name: deploy

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build Vue
        uses: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "se-g18"
          entrypoint: "src/server/entry.ts"
